//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendency
    {
        public string Id { get; set; }
        public string Enter { get; set; }
        public string Exit { get; set; }
        public string Date { get; set; }
        public string UserId { get; set; }
        public string CourseId { get; set; }
    }
}
