//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnSpotEntities : DbContext
    {
        public OnSpotEntities()
            : base("name=OnSpotEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<attendancy> attendancy { get; set; }
        public virtual DbSet<course> course { get; set; }
        public virtual DbSet<lesson> lesson { get; set; }
        public virtual DbSet<student_to_course> student_to_course { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
